stages:
 - staging
 - production

otc-staging:
  stage: staging
  script:
    - echo $CI_PROJECT_DIR
    - rm -rf ~/58otc
    - /bin/cp -r $CI_PROJECT_DIR ~
#    - find ~/58otc -name 'package-lock.json' -exec rm -rf {} \;
    - /bin/cp ~/58otc/api.config.js.prod ~/58otc/config/api.config.js
    - cd ~/58otc
    - echo `pwd`
    - sudo docker build -f Dockerfile -t otc:$CI_COMMIT_TAG .
    - sudo docker tag otc:$CI_COMMIT_TAG 23.99.114.54:5000/otc:$CI_COMMIT_TAG
    - sudo docker push 23.99.114.54:5000/otc:$CI_COMMIT_TAG
    - sleep 3
    - ssh 58coin@23.99.114.54 "docker service update --image 10.0.5.6:5000/otc:$CI_COMMIT_TAG 58c2c_staging"
  only:
    - tags
  tags:
    - ip-65-186

otc-production:
  stage: production
  script:
    - ssh 58coin@23.99.114.54 "docker service update --image 10.0.5.6:5000/otc:$CI_COMMIT_TAG 58c2c_prod"
  only:
    - tags
  when: on_success
  tags:
    - ip-65-186
